### ISSUE TITLE
Deliveries

### ISSUE THREAD

**Issue by mbabazigift** [UNFPAInnovation/GetIN-Web-2.0#3]
GIVEN that a DHO wants to track the number of successful deliveries Vs stillborn deliveries of the girls that have been mapped THEN he should be able to find a provision in the side navigation bar of the web dashboard and once he clicks on it, he should be able to see detailed information of the relevant information. 

**Acceptance Criteria**
- The DHO should be able to filter through the information in the table based on a particular date they enter.
- The DHO should be able to view the kind of follow up done on the home births and if the mother has received postnatal care yet.

**Comment by mbabazigift** [comment]
- Remove the health facility column under the health facility delivery card.
- Capture postnatal care information on both the health facility and home card.

**Comment by thenebbiking** [comment]
@mbabazigift 

- Health facility removed.
- For postnatal care, do you want us to show Yes or No if postnatal care was provided?

**Comment by mbabazigift** [comment]
@thenebbiking 

Yes, let's capture the NO, YES response under postnatal care.

**Comment by innyanzi** [comment]
@mbabazigift please review to ensure that the update meets the requirements.
![deliveries](https://user-images.githubusercontent.com/50903508/70532173-909cd480-1b67-11ea-9540-dbd4ba36579b.png)

**Comment by mbabazigift** [comment]
Resolved.
