### ISSUE TITLE
Dashboard Mapped girls card

### ISSUE THREAD

**Issue by richardzulu** [UNFPAInnovation/GetIN-Web-2.0#32]
Given that I have logged in as a DHO and there are mapped girls in the system over a certain period WHEN I visit the dashboard home page THEN I cannot view the number of mapped girls within a given period in the dashboard card over the same period of time.

**Acceptance criteria**

+ The dashboard card for Number of girls mapped should always show the count for the number of girls in the database

**Comment by thenebbiking** [comment]
Closed with backend fix. See #https://github.com/UNFPAInnovation/GetInServerRebuild/commit/f18cc06412dd65c9600eb1850cac7d7553926886
