### ISSUE TITLE
Show date for mapped girls

### ISSUE THREAD

**Issue by richardzulu** [UNFPAInnovation/GetIN-Web-2.0#34]
The mapped girl's table should show the date column for when the record was added.

<img width="1021" alt="Screenshot 2019-12-02 at 21 59 52" src="https://user-images.githubusercontent.com/244889/69987387-7738ce80-1550-11ea-856f-abac7f4060f1.png">

**Comment by richardzulu** [comment]
@thenebbiking Is it possible to please have it in the format of dd-mm-yyyy rather than yyyy-mm-dd?

**Comment by thenebbiking** [comment]
@Richardzulu yes it is. Going to standardize the format of the dates all through the dashboard

**Comment by innyanzi** [comment]
@mbabazigift, please review to ensure that the update meets the requirements.
![Search by first name](https://user-images.githubusercontent.com/50903508/70533232-b0cd9300-1b69-11ea-856d-eb01e9d8284e.png)

**Comment by mbabazigift** [comment]
Resolved.
