### ISSUE TITLE
Follow ups

### ISSUE THREAD

**Issue by mbabazigift** [UNFPAInnovation/GetIN-Web-2.0#4]
GIVEN that the DHO wants to track how the health workers are working together with the young pregnant girls THEN he should be able to click on a provision in the side navigation menu, that when clicked will lead the user to a page with the relevant information.

**Acceptance Criteria**
- The DHO should be able to filter through the information in the table based on a particular date they enter. 
- The DHO should be able to filter through by health facility.
- The DHO should be able to follow up with the health facilities that have the highest number of girls missing ANC and know the reasons for missing.

**Comment by mbabazigift** [comment]
- Capture the follow-up date.

**Comment by thenebbiking** [comment]
@mbabazigift 

For the follow up date, do you want the date the followup is captured / made or the date the girl is supposed to be followed up showed?

**Comment by mbabazigift** [comment]
@thenebbiking 
The date when the follow up was captured by the health worker.

**Comment by innyanzi** [comment]
@mbabazigift , please review to ensure that the update resolved the issues.
![followups](https://user-images.githubusercontent.com/50903508/70532340-e3768c00-1b67-11ea-9115-2e8c015bb02a.png)

**Comment by mbabazigift** [comment]
Resolved.
