### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by mbabazigift** [UNFPAInnovation/GetIN-Web-2.0#6]
GIVEN that a DHO wants to keep track of the health workers' activities on how they are using the application THEN he should be able to click on a provision in the side navigation menu, that when clicked will lead him to a page with the relevant information. 

**Acceptance Criteria**
- The DHO should be able to filter through the information in the table based on a particular date they enter. 
- The DHO should be able to filter through by health facility.

**Comment by mbabazigift** [comment]
According to the so far developed feature in the dashboard the following need to be added;
- For each user add their personal phone numbers (midwife, CHEW and ambulance)
- For each user add their GetIN phone numbers (midwife and CHEW)
- Name of the health facility.
- Village and sub-county.
- Name of a midwife for the CHEW feature and list of CHEWs for the midwife feature.

**Comment by mbabazigift** [comment]
- Add a sub-county filter on the Add CHEW Form.
- Show respective validation error messages upon submitting invalid data on Add Users forms.

**Comment by mbabazigift** [comment]
@innyanzi 
- Add more columns to capture; sub-county, health facility, GetIN contact, personal contact.
- VHTs and midwives have all been listed under VHTs, need to separate the users.
- Change CHEWs to VHTs.

**Comment by innyanzi** [comment]
@mbabazigift ,please review to ensure that the update resolves the issues.
@codephillip, please format the error messages in a standard conversion, refer to this [doc](https://blog.restcase.com/rest-api-error-handling-problem-details-response/) to guide you on that. 
 
![Add VHT](https://user-images.githubusercontent.com/50903508/70532530-4f58f480-1b68-11ea-9acf-670e4b22ca5a.png)
![ambulances](https://user-images.githubusercontent.com/50903508/70532531-4f58f480-1b68-11ea-9cdf-5803ab03e4fb.png)
![midwives](https://user-images.githubusercontent.com/50903508/70532533-4ff18b00-1b68-11ea-92fd-a2f575ceec7a.png)
![vht](https://user-images.githubusercontent.com/50903508/70532534-508a2180-1b68-11ea-89d2-b5a7e614d347.png)

**Comment by mbabazigift** [comment]
@codephillip the backend should be able to capture the GetIN phone number.

**Comment by mbabazigift** [comment]
@innyanzi 
- Make email addresses optional to users for some may not have an email. 
- Users should be able to filter by name, village, and sub-county.
