### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by mbabazigift** [UNFPAInnovation/GetIN-Web-2.0#8]
GIVEN that a user wants to manage other users, manage org units AND change their password THEN they should be able to go to the setting's provision in the side navigation bar and do so. 

**Acceptance Criteria**
- There are 2 types of dashboard users: an administrator and a DHO. 
- An administrator should be able to make system changes like managing org units and passwords within the system. 
- A DHO should only be able to change users and some of the org units.

**Comment by mbabazigift** [comment]
- Add manage columns i.e sub-county, health facility, GetIN contact, personal contact.
- Separate VHTs from midwives, all users have been placed under VHTs.
- Change CHEWs to VHTs.

**Comment by innyanzi** [comment]
Duplicate of #6

**Comment by mbabazigift** [comment]
Resolved.
